services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - aware-network

  kafka:
    image: docker.io/bitnami/kafka:2.8
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:9093,EXTERNAL://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka:9093,EXTERNAL://localhost:9092
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
    depends_on:
      - zookeeper
    networks:
      - aware-network

  cloud:
    image: cloud
    hostname: cloud
    container_name: cloud
    depends_on:
      - zookeeper
      - redis
    environment:
      BROKER: redis
      PORT: 6379
      TOPIC: traffic
      URL: https://api.airplanes.live/v2/point/36.1716/-115.1391/200
    networks:
      - aware-network
  
  puddle:
    image: puddle
    hostname: puddle
    container_name: puddle
    depends_on:
      - cloud
    environment:
      BROKER: redis
      PORT: 6379
      TOPIC: traffic
    networks:
      - aware-network

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    networks:
      - aware-network

networks:
  aware-network:
    driver: bridge
    name: aware_network
